---
title: "Fii_Script_Opt"
author: "Marcus Antonio Cardoso Ramalho"
date: "08/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}

library(tidyverse)
library(lubridate)
library(highcharter)
library(tidyquant)
library(tibbletime)
library(quantmod)
library(PerformanceAnalytics)
library(PortfolioAnalytics)
library(timetk)
library(plotly)
library(readxl)

###############################################################################
#
#Calculo dos retornos
#
###############################################################################

#Baixa os preços dos ativos salvos no vetor ativos


ativos<-carteira_final$Ticker

pricesfii <- 
  getSymbols(ativos, 
             src = "yahoo", 
             from = "2017-01-02",
             to = "2019-12-31",
             auto.assign = TRUE, 
             warnings = FALSE,) %>% 
  map(~Ad(get(.))) %>% 
  reduce(merge) %>%
    `colnames<-`(ativos)%>%
  na.omit()

#Calculo dos retonos

 assetfii_returns_dplyr_byhand <- 
  pricesfii %>%  # converter o índice para data
  data.frame(date = index(.)) %>%
  remove_rownames() %>% 
  gather(asset, returns, -date) %>% 
  group_by(asset) %>%
  mutate(returns = ((log(returns) - log(lag(returns)))))%>%
   na.omit()
 
 
```

```{r}
###############################################################################
#
#Otimização.
#Script adaptado de www.codingfinance.com/post/2018-05-31-portfolio-opt-in-r/
#
###############################################################################
#guarda os retornos já calculados
mean_ret <- colMeans(assetfii_returns_xts)

cov_mat <- cov(assetfii_returns_xts)

#criando um vetor de pesos com pesos temporários





#a soma dos pesos deve ser igual a 1

print(sum(wts))


port_returns <- (sum(wts * mean_ret))


port_risk <- sqrt(t(wts) %*% (cov_mat %*% wts))

  
sharpe_ratio <- port_returns-rfr/port_risk


#numero de portifólios a serem gerados
num_port <- 5000

# Matriz para guardar os pepsos

all_wts <- matrix(nrow = num_port,
                  ncol = length(ativos))

#vetor vazio para guardar os retornos

port_returns <- vector('numeric', length = num_port)

#vetor vazio de registro do desvio padrão

port_risk <- vector('numeric', length = num_port)

#criando um vetor para armazzenar o indice sharpe posteriormente

sharpe_ratio <- vector('numeric', length = num_port)



for (i in seq_along(port_returns)) {
  
  wts <- runif(length(ativos))
  wts <- wts/sum(wts)
  

  
  all_wts[i,] <- wts
  
  # calculo dos retornos do portifolio
  
  port_ret <- sum(wts * mean_ret)

  
  # Guardando os retornos
  port_returns[i] <- port_ret
  
  
  # Calculando o risco do portifolio
  port_sd <- sqrt(t(wts) %*% (cov_mat  %*% wts))
  port_risk[i] <- port_sd
  
  # Calculando o índice sharpe

  
  sr <- (port_ret-0.0058
)/port_sd
  sharpe_ratio[i] <- sr
  
}


# Guardando os valores
portfolio_values <- tibble(Return = port_returns,
                  Risk = port_risk,
                  indice_Sharpe = sharpe_ratio)




# Convertendo a matriz em tibble
all_wts <- tk_tbl(all_wts)

colnames(all_wts) <- colnames(assetfii_returns_xts)

# Combinando os valores
portfolio_values <- tk_tbl(cbind(all_wts, portfolio_values))

head(portfolio_values)

min_var <- portfolio_values[which.min(portfolio_values$Risk),]
max_sr <- portfolio_values[which.max(portfolio_values$indice_Sharpe),]

p1 <- min_var %>%
  gather(1:24, key = Asset,
         value = Weights) %>%
  mutate(Asset = as.factor(Asset)) %>%
  ggplot(aes(x = fct_reorder(Asset,Weights), y = Weights, fill = Asset)) +
  geom_bar(stat = 'identity') +
  theme_minimal() +
  labs(x = 'Fundos', y = 'Pesos', title = "Pesos do portifólio de variância mínima") +
  scale_y_continuous(labels = scales::percent) 


p2 <- max_sr %>%
  gather(1:24, key = Asset,
         value = Weights) %>%
  mutate(Asset = as.factor(Asset)) %>%
  ggplot(aes(x = fct_reorder(Asset,Weights), y = Weights, fill = Asset)) +
  geom_bar(stat = 'identity') +
  theme_minimal() +
  labs(x = 'Fundos', y = 'Pesos', title = "Pesos do portifólio tangente") +
  scale_y_continuous(labels = scales::percent) 


p3 <- portfolio_values %>%
  ggplot(aes(x = Risk, y = Return, color = indice_Sharpe)) +
  geom_point() +
  theme_classic() +
 labs(x = 'Risco',
       y = 'Retorno',
       title = "Otimização do portifólio e fronteira eficiente") +
   scale_y_continuous(labels = scales::percent,expand = c(0, 0), limits = c(0, 0.02)) +
  scale_x_continuous(labels = scales::percent,expand = c(0, 0), limits = c(0, 0.04)) +
  geom_point(aes(x = Risk,
                 y = Return), data = min_var, color = 'green') +
  geom_point(aes(x = Risk,
                 y = Return), data = max_sr, color = 'red')+
  annotate(geom = 'segment', x = 0, xend = 0.027,  y = 0.0058, 
           yend = 0.014, color = 'red')+
   annotate('text', x = 0.0025, y = 0.0058,label="SELIC" )+
   annotate('point', x = 0, y = 0.0058,color="black" )+
   annotate('point', x = 0.027, y = 0.014,color="black" )+
   annotate('text', x =  0.028, y = 0.0148, label = "IFIX")+
   annotate('text', x = 0.020, y = 0.011, label = "V.M")+
   annotate('text', x = 0.024, y = 0.0145, label = "P.T")
  
  


p3

ggplotly(p1)
ggplotly(p2)
#ggplotly(p3)


```
########################################################################

```{r}
#Calculo de beta
Beta_portifolio_ifix<-
  cov(portifoliofii_monthly_returns_dplyr_byhand$returns,Retornos_ifix$returns)/var(portifoliofii_monthly_returns_dplyr_byhand$returns)
Beta_portifolio_ifix

#Plot do gráfico de correlação

comb_ret<-left_join(portifoliofii_monthly_returns_dplyr_byhand,Retornos_ifix, by = 'date')

comb_ret %>%
  ggplot(aes(x = portifoliofii_monthly_returns_dplyr_byhand$returns,
             y = Retornos_ifix$returns)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = 'lm',
              se = TRUE) +
  theme_classic() +
  labs(x = 'Retornos IFIX',
       y = "Retornos do portifólio",
       title = "Retornos do portifólio vs retornos do IFIX - Portifólio de variância mínima") +
  scale_x_continuous(breaks = seq(-0.1,0.1,0.01),
                     labels = scales::percent) +
  scale_y_continuous(breaks = seq(-0.1,0.1,0.01),
                     labels = scales::percent)


#Exemplo de cálculo do desvio padrão

  Retornos_ifix %>%
  summarise(dplyr = sd(returns)) %>%
  mutate(dplyr = round(dplyr, 4) * 100)
  
  mean(Retornos_ifix$returns)
  
  

```

