---
title: "optmization_2022"
author: "Marcus Antonio Cardoso Ramalho"
date: "2022-10-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyquant) # To download the data
library(plotly) # To create interactive charts
library(timetk) # To manipulate the data series
library(plotly)
library(tidyverse)
```

```{r}


portfolio <- read_delim("dados/carteira_final.txt")
(tick<-portfolio$Ticker)

Rfr<-0.02

price_data <- tq_get(tick,
                     from = '2017-01-02',
                     to = '2019-12-31',
                     get = 'stock.prices')

#Next we will calculate the daily returns for 
#these stocks. We will use the logarithmic returns.

log_ret_tidy <- price_data %>%
  group_by(symbol) %>%
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = 'daily',
               col_rename = 'ret',
               type = 'log')

head(log_ret_tidy)
```

```{r}

# As you can see that this data is in tidy format. 
#We will use the spread() function to convert it to a wide format. 
#And we will also convert it into a time series object using xts() function.
log_ret_xts <- log_ret_tidy %>%
  spread(symbol, value = ret) %>%
  tk_xts()

head(log_ret_xts)

```


```{r}
#Next lets calculate the mean daily returns for each asset.
mean_ret <- colMeans(log_ret_xts)
print(round(mean_ret, 5))

#Next we will calculate the covariance matrix for all these stocks.
#We will annualize it by multiplying by 252.

cov_mat <- cov(log_ret_xts) * 252
round(cov_mat,4)

num_port <- 5000

# Creating a matrix to store the weights

all_wts <- matrix(nrow = num_port,
                  ncol = length(tick))

# Creating an empty vector to store
# Portfolio returns

port_returns <- vector('numeric', length = num_port)

# Creating an empty vector to store
# Portfolio Standard deviation

port_risk <- vector('numeric', length = num_port)

# Creating an empty vector to store
# Portfolio Sharpe Ratio

sharpe_ratio <- vector('numeric', length = num_port)

```

```{r}

#Next lets run the for loop 5000 times.

for (i in seq_along(port_returns)) {
  
  wts <- runif(length(tick))
  wts <- wts/sum(wts)
  
  # Storing weight in the matrix
  all_wts[i,] <- wts
  
  # Portfolio returns
  
  port_ret <- sum(wts * mean_ret)
  port_ret <- ((port_ret + 1)^252) - 1
  
  # Storing Portfolio Returns values
  port_returns[i] <- port_ret
  
  
  # Creating and storing portfolio risk
  port_sd <- sqrt(t(wts) %*% (cov_mat  %*% wts))
  port_risk[i] <- port_sd
  
  # Creating and storing Portfolio Sharpe Ratios
  # Assuming 0% Risk free rate
  
  sr <- (port_ret-Rfr)/port_sd
  sharpe_ratio[i] <- sr
  
}

```

```{r}

# Storing the values in the table
portfolio_values <- tibble(Return = port_returns,
                           Risk = port_risk,
                           SharpeRatio = sharpe_ratio)


# Converting matrix to a tibble and changing column names
all_wts <- tk_tbl(all_wts)

colnames(all_wts) <- colnames(log_ret_xts)

# Combing all the values together
portfolio_values <- tk_tbl(cbind(all_wts, portfolio_values))

#The minimum variance portfolio
#The tangency portfolio (the portfolio with highest sharpe ratio)

min_var <- portfolio_values[which.min(portfolio_values$Risk),]
max_sr <- portfolio_values[which.max(portfolio_values$SharpeRatio),]



#Lets plot the weights of each portfolio. First with the minimum variance portfolio.


  
  
  #annotate('text', x = 0.20, y = 0.42, label = "Tangency Portfolio") +
 # annotate('text', x = 0.18, y = 0.01, label = "Minimum variance portfolio") +
 # annotate(geom = 'segment', x = 0.14, xend = 0.135,  y = 0.01, 
        #   yend = 0.06, color = 'red', arrow = arrow(type = "open")) +
  #annotate(geom = 'segment', x = 0.22, xend = 0.2275,  y = 0.405, 
         #  yend = 0.365, color = 'red', arrow = arrow(type = "open"))


#ggplotly(p)









```



```{r}

(min_var_2p)
(max_sr_2p)

(min_var)
(max_sr)

comparativo<-rbind(min_var_2p,min_var,max_sr_2p,max_sr) #variancia min (2%) etc...

comparativo<-comparativo %>% 
  rowid_to_column("port_number")#adicionando o numero de cada portifolio 

table_risk_return_sharpe_by_port<-comparativo %>% 
  select(port_number,Return,Risk,SharpeRatio)

table_comp_Ticker<-comparativo%>% 
pivot_longer(cols = ABCP11.SA:XPCM11.SA, #Alongando a tabela para receber as categorias
             names_to = "Ticker",
             values_to = "weight")  
  
table_comp_Ticker<-table_comp_Ticker %>% 
  inner_join(portfolio,comparativo,by="Ticker")  #adiciona as categorias
  
  table_comp_Ticker$Categoria<- as_factor(table_comp_Ticker$Categoria)
  
  
  view(table_comp_Ticker)
  
##
  
table_comp_Sector2<-table_comp_Ticker %>% 
  select(port_number,Ticker,Categoria,weight,everything()) %>%#Soma dos pesos por categoria !!funcionando
  group_by(Categoria, port_number) %>% 
  summarise(count=n(),sum_weights=sum(weight))

  table_comp_Sector2<-table_comp_Sector2 %>% 
    arrange(port_number)

  view(table_comp_Sector2)
  
  #table_comp_Sector_complete<-inner_join(table_comp_Sector2,table_risk_return_sharpe_by_port,by="port_number")
  
  #table_comp_Sector_complete<-table_comp_Sector_complete %>% 
    #arrange(port_number)
  
  
  #view(table_comp_Sector_complete)
    
  
  
  
  
  
 
  

  
  
  
  #table_comp_Sector<-table_comp_Ticker %>% 
  #select(port_number,Ticker,Categoria,weight,everything()) %>%#Soma dos pesos por categoria
  #group_by(port_number) %>%
  #group_by(Categoria) %>% 
  #summarise(sum_weights=sum(weight),port_number=port_number,Return=Return,Risk=Risk,SharpeRatio=SharpeRatio)


#view(table_comp_Sector)

```

```{r}

library(kableExtra)

table_comp_Sector2$Categoria <- str_wrap(table_comp_Sector2$Categoria, width = 10)

tbl_1_2<-filter(table_comp_Sector2,port_number=="min_var_2%"|port_number=="min_var_13%")#filtra os portifolios de minima variancia para taxas de 2% e 5%

table_comp_Sector2$port_number[which(table_comp_Sector2$port_number=="1")]<-"min_var_2%"
table_comp_Sector2$port_number[which(table_comp_Sector2$port_number=="2")]<-"min_var_13%"
table_comp_Sector2$port_number[which(table_comp_Sector2$port_number=="3")]<-"tangent_2%"
table_comp_Sector2$port_number[which(table_comp_Sector2$port_number=="4")]<-"tangent_13%"

#plota a distribuicao de peso por categoria para os portifolios de minima variancia
ggplot(tbl_1_2) +
  aes(x = fct_reorder(Categoria,sum_weights), y = sum_weights, fill = Categoria) +
  geom_col(position="dodge2") +
  facet_wrap(~port_number,nrow=2)+
  labs(x = 'Category', y = 'Weight', title = "Portfolio weight distribution by Category - Min Variance portfolio")+
  theme_minimal()

tbl_3_4<-filter(table_comp_Sector2,port_number=="tangent_2%"|port_number=="tangent_13%")#filtra os portifolios tangentes

#plota a distribuicao de peso por categoria para os portifolios tangentes
ggplot(tbl_3_4) +
  aes(x = fct_reorder(Categoria,sum_weights), y = sum_weights, fill = Categoria) +
  geom_col(position="dodge2") +
  facet_wrap(~port_number,nrow=2)+
  labs(x = 'Category', y = 'Weight', title = "Portfolio weight distribution by Category - Tangent portfolio")+
  theme_minimal()


names_port<-c("min_var_2%","min_var_13%","tangent_2%","tangent_13%")
table_risk_return_sharpe_by_port$port_number<-names_port 

table_risk_return_sharpe_by_port<-rename(table_risk_return_sharpe_by_port,portfolio=port_number)
table_comp_Sector2<-rename(table_comp_Sector2,portfolio=port_number)

table_1<-kable((table_risk_return_sharpe_by_port[1:3]), align=rep('c', 3)) %>% 
  kable_styling(full_width = F, position = "left")

kable((table_comp_Sector2[1:4]), align=rep('c', 4)) %>% 
  kable_styling(full_width = F, position = "left")


#rio::export(table_comp_Sector2,"tbl_weights.xlsx")

```


```{r}
#selic_hist<-rio::import("SELIC_HIST.xlsx")

selic_hist <- read_excel("SELIC_HIST.xlsx", 
    col_types = c("date", "numeric"))

IFIX_Mensal_2012_2022 <- read_excel("IFIX_Mensal_2012_2022.xlsx", 
    col_types = c("date", "numeric"))

IFIX_Mensal_2012_2022_ts<-tk_xts(IFIX_Mensal_2012_2022)

IFIX_Mensal_2012_2022_ts <-
  IFIX_Mensal_2012_2022_ts %>% 
  to.monthly(indexAt = "lastof",
             OHLC = FALSE) %>% 
  window(start="2013-01-31")
  

selic_hist_ts<-tk_xts(selic_hist)

selic_hist_ts <- selic_hist_ts %>% 
    to.monthly(indexAt = "lastof",
               OHLC = FALSE) %>% 
  window(start="2013-02-28")


log_ret_IFIX <-Return.calculate(IFIX_Mensal_2012_2022_ts, 
                   method = "log") %>% 
                   na.omit()



comp_ifix_selic<-cbind(selic_hist_ts,
                       log_ret_IFIX)

comp_ifix_selic<-tk_tbl(comp_ifix_selic)

comp_ifix_selic<-comp_ifix_selic %>% 
  rename(date=index) %>% 
  remove_rownames() %>% 
  pivot_longer(names_to = "asset",values_to = "returns",-date) %>%

 
  


# rio::export(comp_ifix_selic,"comp_ifix_selic.xlsx")


# comp_ifix_selic <- readxl::read_excel("comp_ifix_selic.xlsx", 
#     col_types = c("date", "numeric", "text"))


ggplot(comp_ifix_selic) +
  aes(x = date, y = returns, colour = asset) +
  geom_line(size = 0.5) +
  scale_color_hue(direction = 1) +
  theme_minimal()+
  labs(title = "Comparative returns IFIX vs SELIC - 2013-2022")








```

